-- Este arquivo nao cria usuarios ou senhas de demonstracao.
-- Depois de aplicar schema.sql, configure DATABASE_URL, ADMIN_EMAIL e
-- ADMIN_PASSWORD apenas no terminal local e execute: npm run create-admin
